## all stages
external:
    machine: 'perl'

global:
    experiment: 'so'
    nside: 256
    cov_correction: 'w2' # 'w2' # w2 factor, fsky, none (null)
    template: 'p353' # 'p353'

bandpowers:
    lmin: 30
    dell: 30
    nbands: 9
    
mask:
    mask_type: 'soflat'
    apo_deg: 5.0
    smooth_deg: 0.4
    dell_nmt: 10

polarization:
    pol_cov: 'B'

components:
    dust: True
    sync: True

paths:
    output_path: '/global/cfs/cdirs/act/data/iabril/BBPower/230324/'
    bicep_BK15: '/global/cfs/cdirs/act/data/iabril/BICEP/'
    bbpipe_path: '/global/cfs/cdirs/act/software/iabril/condaenvs/github_reps/BBPower/'
    planck_path_cori: '/global/cscratch1/sd/iabril/PlanckData/'
    planck_path_perl: '/pscratch/sd/i/iabril/data/PlanckData/'
    camb_cmb_lens_nobb: '/global/cfs/cdirs/act/software/iabril/condaenvs/github_reps/BBPower/examples/data/camb_lens_nobb.dat'
    so_path: '/global/cfs/cdirs/act/data/iabril/SO/'
    template_path: '/global/cfs/cdirs/act/data/iabril/DustFilaments/'

cosmology:

    CMB:
        Alens: 1.

    dust:

        A_dust_BB: 28. # from BICEP field 1510.09217
        EB_dust: 2. # PL amplitude 1801.04945
        alpha_dust_EE: -0.42 # PL exponent 1801.04945
        alpha_dust_BB: -0.54 # PL exponent 1801.04945
        beta_dust: 1.59 # modified BB emission 1409.5738
        temp_dust: 19.6 # modified BB emission 1409.5738
        nu0_dust: 353.

    sync:

        A_sync_BB: 2.0
        EB_sync : 2.
        alpha_sync_EE : -0.6
        alpha_sync_BB : -0.4
        beta_sync : -3.
        nu0_sync : 23.

    model:
        lnorm_PL: 80.        # PL param 1801.04945
    
band_names:
    SO: ['LF1', 'LF2', 'MF1', 'MF2', 'UHF1', 'UHF2']
    BICEP: ['95', '150', '220']

dust_filaments:
    nsims: 200
    paths:
        base: '/global/cfs/cdirs/act/data/iabril/DustFilaments/'
        sim:  'sims_230306/'
        output: 'analysis_230324/'
        base_name: 'DustFilaments_TQU_180p5M_400pc_LR71_GNILC-unires_ell-limit50_nside512_reso12-25_seed'
        mid_name: 'ScaleMap_f'
        end_name: 'p0.fits'


#    nparams: 8 # + 1 if cross, + 4 if moments