## all stages
external:
    machine: 'perl'

global:
    experiment: 'so'
    nside: 256

bandpowers:
    lmin: 2
    dell: 10
    nbands: 50
    
mask:
    mask_type: 'so'
    apo_deg: 5.
    smooth_deg: 40.
    dell_nmt: 10

polarization:
    pol_cov: 'B'

components:
    dust: True
    sync: False

paths:
    output_path: '/global/cfs/cdirs/act/data/iabril/BBPower/pipeline_test/'
    bicep_BK15: '/global/cfs/cdirs/act/data/iabril/BICEP/'
    bbpipe_path: '/global/cfs/cdirs/act/software/iabril/condaenvs/github_reps/BBPower/'
    planck_path_cori: '/global/cscratch1/sd/iabril/PlanckData/'
    planck_path_perl: '/pscratch/sd/i/iabril/data/PlanckData/'
    camb_cmb_lens_nobb: '/global/cfs/cdirs/act/software/iabril/condaenvs/github_reps/BBPower/examples/data/camb_lens_nobb.dat'
    so_path: '/global/cfs/cdirs/act/data/iabril/SO/'

cosmology:

    CMB:
        Alens: 1.

    dust:

        A_dust_BB: 5.0 # from BICEP field 1510.09217
        EB_dust: 2. # PL amplitude 1801.04945
        alpha_dust_EE: -0.42 # PL exponent 1801.04945
        alpha_dust_BB: -0.2 # PL exponent 1801.04945
        beta_dust: 1.59 # modified BB emission 1409.5738
        temp_dust: 19.6 # modified BB emission 1409.5738
        nu0_dust: 353.

    sync:

        A_sync_BB: 2.0
        EB_sync : 2.
        alpha_sync_EE : -0.6
        alpha_sync_BB : -0.4
        beta_sync : -3.
        nu0_sync : 23.

    model:
        lnorm_PL: 80.        # PL param 1801.04945

band_names:
    SO: ['LF1', 'LF2', 'MF1', 'MF2', 'UHF1', 'UHF2']
    BICEP: ['95', '150', '220']


