global:
  freq: 353
  nside: 512
  mask: 'soflat'
  nsims: 200
  lmin: 30
  lmax: 300
  dell: 30
  type_cov: 'df00'
#  isDell: False

paths:
  base: '/global/cfs/cdirs/act/data/iabril/DustFilaments/'
  sim:  'sims_230306/'
  output: 'analysis/'
  base_name: 'DustFilaments_TQU_180p5M_400pc_LR71_GNILC-unires_ell-limit50_nside512_reso12-25_seed'
  mid_name: 'ScaleMap_f'
  end_name: 'p0.fits'

norm:
  alphad: -0.54
  ampd  : 28.
