## all stages
global:
    experiment: 'bicep'
    machine: 'perl'
    nside: 256

bandpowers:
    lmin: 10
    dell: 35
    nbands: 9
    
mask:
    mask_type: 'full'
    apo_deg: .NAN
    smooth_deg: 20.
    dell_nmt: 10


polarization:
    pol_cov: 'B'

paths:
    output_path: '/global/cfs/cdirs/act/data/iabril/BBPower/pipeline_test/'

cosmology:

    CMB:
        Alens: 1.0

    dust:

        A_dust_BB: 5.0 # from BICEP field 1510.09217
        EB_dust: 2. # PL amplitude 1801.04945
        alpha_dust_EE: -0.42 # PL exponent 1801.04945
        alpha_dust_BB: -0.2 # PL exponent 1801.04945
        beta_dust: 1.59 # modified BB emission 1409.5738
        temp_dust: 19.6 # modified BB emission 1409.5738
        nu0_dust: 353.

    model:
        lnorm_PL: 80.        # PL param 1801.04945

band_names:
    SO: ['LF1', 'LF2', 'MF1', 'MF2', 'UHF1', 'UHF2']
    BICEP: ['95', '150', '220']

