global_emcee:
  niter: 10000
  nwalk: 128
  nside: 256
  
ranges:
  lmin: 30
  lmax: 300
#  bands: 

bands_iter:
  so: ['all',  ['LF1', 'LF2'], ['MF1', 'MF2'], ['UHF1', 'UHF2'] ] # , ['LF1', 'MF1', 'UHF2'], ['MF1','UHF2']] # ['LF1','LF2','MF1','MF2','UHF2']] #
  other: ['all']